### ISSUE TITLE
Verification issues

### ISSUE THREAD

**Issue by brianwang9100** [bitpay/spree-bitpay#15]
### ChangingPaymentMethod
1. When on confirm page, you can no longer change payment by pressing the edit link in the confirm area or pressing the payment tab at the top border. The only way to change order is to go back to the original cart/ account information and then proceed to payment options.

2. Pressing placing order and then proceeding to click on the change payment option doesn’t go directly to the payment option, just starts over from the cart. 

### PostPaymentIssues

1. After completion of purchase, cart does not empty completely.

After payment
![screen shot 2015-06-17 at 2 22 18 pm](https://cloud.githubusercontent.com/assets/7969184/8215179/51731a56-14fc-11e5-95a6-0ee2ac4e7b9e.png)
Pressing home
![screen shot 2015-06-17 at 2 22 29 pm](https://cloud.githubusercontent.com/assets/7969184/8215183/5a4d09f2-14fc-11e5-976b-6c060564be26.png)
Pressing on cart
![screen shot 2015-06-17 at 2 23 23 pm](https://cloud.githubusercontent.com/assets/7969184/8215206/788ca27e-14fc-11e5-86e5-78bd0695bfe5.png)

2. Order does not show up on admin. I had a payment confirmed for R626862439 but when I went to admin to check it didn't show up.

![screen shot 2015-06-17 at 2 20 05 pm](https://cloud.githubusercontent.com/assets/7969184/8215132/01b4958a-14fc-11e5-81d8-b8e201d92a0b.png)

![screen shot 2015-06-17 at 2 17 05 pm](https://cloud.githubusercontent.com/assets/7969184/8215107/ccd079e2-14fb-11e5-8799-211037badf81.png)

**Comment by philosodad** [comment]
The order and cart problems will happen if the plugin cannot receive IPNs from BitPay, for example, if testing on test.bitpay.com from a locally hosted cart.

**Comment by philosodad** [comment]
The edit button is not easily changed for just bitpay, any change would be essentially universal.
